### ISSUE TITLE
Hardcoded linux libc

### ISSUE THREAD

**Issue by bbkr** [mempko/PKafka#1]
Hi

https://github.com/mempko/PKafka/blob/master/lib/PKafka/Native.pm6#L26 has hardcoded library name, and .so extension does not work under OS X (it uses dylib).

I asked on IRC how to resolve this issue and it appears you don't have to specify library name at all since libc is already loaded, so:

```
my $errno := cglobal(Str, 'errno', int);
```

should work.

**Comment by ah-** [comment]
Alternatively, there's now rd_kafka_errno: https://github.com/edenhill/librdkafka/commit/d91491184ccff8faca763f9e195656fb9d9f7746

**Comment by mempko** [comment]
Good catch. Om away from my computer. Oll fix it as soon as possible.

**Comment by mempko** [comment]
I pushed the fix. Let me know if it works now so I can close the issue.

**Comment by mempko** [comment]
@bbkr ::touched gently::

**Comment by bbkr** [comment]
Sorry about the delay.

I've tested connection issues (killing server) and it looks like it catches errors properly on OS X.

Thanks for quick fix!
