### ISSUE TITLE
Simplified BUILDs

### ISSUE THREAD

**Issue by bbkr** [mempko/PKafka#2]
Hi

BUILD allow to initialize class arguments directly from signature through `:$!name` syntax, so for example:

```
    submethod BUILD(
        Str :$topic!, 
        PKafka::Config :$config, 
        PKafka::TopicConfig :$topic-config,
        Str :$brokers!) 
    {
        $!config = $config ?? $config !! PKafka::Config.new;
        $!topic-config = $topic-config ?? $topic-config !! PKafka::TopicConfig.new; 
        ...
    }
```

can be simply written as

```
    submethod BUILD(
        Str :$topic!, 
        PKafka::Config :$!config, 
        PKafka::TopicConfig :$!topic-config,
        Str :$brokers!) 
    {
        $!config //= PKafka::Config.new;
        $!topic-config //= PKafka::TopicConfig.new; 
         ...
    }
```

Of course TIMTOWTDI, so if you used explicit `??  !!` for some reason (ie. coding standards) feel free to close this issue.

Cheers.

**Comment by mempko** [comment]
Sweet, didn't know about that operator! I'm away from computer. Will give it a try asap.

**Comment by bbkr** [comment]
You can even mix default param values with `:$!name` to initialize attribute:

```
    submethod BUILD(
        Str :$topic!, 
        PKafka::Config :$!config = PKafka::Config.new, 
        PKafka::TopicConfig :$!topic-config = PKafka::TopicConfig.new,
        Str :$brokers!) 
    {
         ...poof, 2 lines less...
    }
```

Some may say it is a bit risky to initialize in signature something that is not immutable and may fail (like PKafkaConfig::BUILD calls rd_kafka_conf_new), but if you don't have to try/catch it then it is even more clean syntax.

**Comment by mempko** [comment]
Done, thanks for pointing it out.
