### ISSUE TITLE
Partition stop can desync with attribute that tracks them.

### ISSUE THREAD

**Issue by bbkr** [mempko/PKafka#4]
https://github.com/mempko/PKafka/blob/master/lib/PKafka/Consumer.pm6#L121

Assigning `%!running{$partition} = False;`  should be done at the end of the method.
Otherwise when rd_kafka_consume_stop returns -1 and X::AdHoc is captured somewhere then it won't be possible to retry stop method because class already unregistered partition.

**Comment by mempko** [comment]
Good find! Will fix asap.

**Comment by mempko** [comment]
Fixed. Thanks for finding the bug!
